-- MySQL Script generated by MySQL Workbench
-- Tue Jun 29 00:43:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delitos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delitos
-- -----------------------------------------------------
DROP DATABASE helpme_iud;

CREATE DATABASE IF NOT EXISTS `helpme_iud` DEFAULT CHARACTER SET utf8 ;
USE `helpme_iud` ;

-- -----------------------------------------------------
-- Table `helpme_iud`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpme_iud`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `helpme_iud`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpme_iud`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(120) NOT NULL,
  `nombre` VARCHAR(120) NULL,
  `password` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `enabled` TINYINT NULL DEFAULT 1,
  `red_social` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `helpme_iud`.`roles_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpme_iud`.`roles_usuarios` (
  `usuarios_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`usuarios_id`, `roles_id`),
  INDEX `fk_usuarios_has_roles_roles1_idx` (`roles_id`),
  INDEX `fk_usuarios_has_roles_usuarios1_idx` (`usuarios_id`),
  CONSTRAINT `fk_usuarios_has_roles_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `helpme_iud`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_roles_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `helpme_iud`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `helpme_iud`.`delitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpme_iud`.`delitos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(200) NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_delitos_usuarios1_idx` (`usuarios_id`),
  CONSTRAINT `fk_delitos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `helpme_iud`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `helpme_iud`.`casos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpme_iud`.`casos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NULL DEFAULT now(),
  `latitud` FLOAT NULL,
  `longitud` FLOAT NULL,
  `altitud` FLOAT NULL,
  `visible` TINYINT NULL DEFAULT 1,
  `descripcion` VARCHAR(200) NULL,
  `usuarios_id` INT NOT NULL,
  `delitos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_casos_usuarios1_idx` (`usuarios_id`),
  INDEX `fk_casos_delitos1_idx` (`delitos_id`),
  CONSTRAINT `fk_casos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `helpme_iud`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_casos_delitos1`
    FOREIGN KEY (`delitos_id`)
    REFERENCES `helpme_iud`.`delitos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

/*POBLACION TIPOS USUARIOS POR SUPERADMIN*/
INSERT INTO roles (nombre,descripcion) 
VALUES ('ROLE_ADMIN', 'administrador del sistema');

INSERT INTO roles (nombre,descripcion) 
VALUES ('ROLE_USER', 'usuarios normales registran casos');

/*POBLACION USUARIOS POR SUPERADMIN*/

INSERT INTO usuarios (username,nombre,password,fecha_nacimiento,enabled,red_social)
VALUES ('julio.martinez@iudigital.edu.co','julio martinez','$2a$10$kbhP/Mqo3JpoYTCtzhccXOPVi/9MekhI3HrNsI78FivjBD2iXtDhe','1985-08-05',1,0);

INSERT INTO usuarios (username,nombre,password,fecha_nacimiento,enabled,red_social)
VALUES ('caro.velasquez8@gmail.com','julio martinez','$2a$10$bwcbu9IMVhg/ElyvGooD9.fh/IXV1Rr8bvhYNIQqFUJr.lZXGkQ/C','1985-08-05',1,0);


INSERT INTO roles_usuarios (usuarios_id,roles_id)
VALUES (1,1);
INSERT INTO roles_usuarios (usuarios_id,roles_id)
VALUES (1,2);
INSERT INTO roles_usuarios (usuarios_id,roles_id)
VALUES (2,2);